spring:
  datasource:
    url: jdbc:h2:mem:credit_application_system_db
    username: Thico
    password: Moura
  jpa:
    showSql: true
    properties:
      hibernate.format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
springdoc:
  swagger-ui:
    path: /swagger-ui.html